#!/bin/bash

brew install wget

#rm -rf gama
mkdir -p gama
cd gama
rm -rfv *.csx

fetch(){
  if [ -f "$1" ]
  then
    echo "exist: $1"
  else
    URL="http://www.gamagama.cn/fetch/$1"
    echo "fetch: $URL"
    wget $URL
  fi
}


fetch 5IbPnUH.csx

fetch IT6Jdkm.csx
fetch 8BwYT2e
fetch COXOA5U.csx
fetch Fp2VzRq
fetch AEutcbZ.csx
fetch 2WlcSid
fetch 3RqXS0i.csx
fetch EH8H2qZ.csx
fetch 7IIKumJ.csx
fetch 2w3zBZ4.csx
fetch Dh7rH2l.csx
fetch 9dzOJ13.csx
fetch 7oDNB5X.csx
fetch GEh2nzA.csx
fetch BAAuo0H.csx
fetch 56PIcLn.csx
fetch ApVuMAi.csx
fetch I2CE4mG.csx
fetch 1SY2u8X.csx
fetch Fzyiy8f.csx
fetch EkiiKz3.csx
fetch 5KwNr5C.csx
fetch EvV4RIb.csx
fetch 5f09w6d.csx
fetch CNtTjVc.csx
fetch G4rwtni.csx
fetch 6GTKomq.csx
fetch GkFQGf1.csx
fetch G6ARs3I.csx
fetch AchL7Zq.csx
fetch BTDIVYx.csx
fetch IZzc8kF.csx
fetch 6ZGELkv.csx
fetch 49vdGXg.csx
fetch 6ni0vrX.csx
fetch HDqNOeo.csx
fetch 2HU14qc.csx
fetch 8nwiDN3.csx
fetch 7Zp2g3h.csx
fetch BiXhgGo.csx
fetch 1cmUyiz.csx
fetch AbHwOXi.csx
fetch FbqpfMG.csx
fetch 013epva.csx
fetch Bi6mXnG.csx
fetch 2EPeBNv.csx
fetch DZioREd.csx
fetch DTwpIZh.csx
fetch Bmx3wik.csx
fetch F3T6xqr.csx
fetch 95lVUvv.csx
fetch HtJP2mi.csx
fetch AynTUsS.csx
fetch EDaOlFJ.csx
fetch 8C2Zv8z.csx
fetch IVCJHsL.csx
fetch 1XOrHmZ.csx
fetch 6CRvoUg.csx
fetch 4X4P6rg.csx
fetch 0MAFaCX.csx
fetch A80R6r8.csx
fetch 5x8Wn7x.csx
fetch GIlmywV.csx
fetch 7ltYRQq.csx
fetch B3hcS7L.csx
fetch EQhYHbN.csx
fetch EG1WHde.csx
fetch 7PRZvGY.csx
fetch 7SPmbv2.csx
fetch 8Qki8Ip.csx
fetch HNtMouH.csx
fetch J78b6ow.csx
fetch 2ktdRkd.csx
fetch Gd48MQM.csx
fetch INhQ6ls.csx
fetch 6qNbRgF.csx
fetch CIw28rT.csx
fetch FexVpcA.csx
fetch 5ocl4VK.csx
fetch FDs45Ya.csx
fetch CqgpXiE.csx
fetch GdT5KT0.csx
fetch 1ENbowR.csx
fetch 7tnk8Fe.csx
fetch 52zQT2h.csx
fetch ArXsZtW.csx
fetch 9qbuEPi.csx
fetch 76nc8I7.csx
fetch J1M2e3F.csx
fetch 0Afxnh5.csx
fetch 3brJb2R.csx
fetch 6EQodrU.csx
fetch 92EYabk.csx
fetch BtSvFhc.csx
fetch 9SeCpF9.csx
fetch ICd7AcC.csx
fetch 9NA86u1.csx
fetch 13NhBdp.csx
fetch Dhry2Os.csx
fetch 0FBnkpS.csx
fetch FmHgrRg.csx
fetch 35yiR3p.csx
fetch 3nMqvrg.csx
fetch 08w3rr9.csx
fetch ICAEEU3.csx
fetch 0Xp1G6R.csx
fetch 804SlNT.csx
fetch 114cKl7.csx
fetch A811lTr.csx
fetch IXImU8a.csx
fetch 7l1Qx8U.csx
fetch 1jZFRMc.csx
fetch Crp2gq2.csx
fetch AVFgmf5.csx
fetch 9bfjfqr.csx
fetch 0mcIs3l.csx
fetch 8tr82jW.csx
fetch 8HSO2b4.csx
fetch FeteblS.csx
fetch DY8qg1E.csx
fetch 9ghAog8.csx
fetch DLqJnkc.csx
fetch HkYuF0P.csx
fetch FaQsyAD.csx
fetch 0UcsUWc.csx
fetch IyLR0h6.csx
fetch GJJOmaJ.csx
fetch 9LUEqzO.csx
fetch 1GoPJgX.csx
fetch 47nbzva.csx
fetch GskP3WX.csx
fetch 95Aks4d.csx
fetch CwST5os.csx
fetch 7ezYOtf.csx
fetch 6YZR7pb.csx
fetch 28zF6iI.csx
fetch 6l5LZKb.csx
fetch GyDCnt8.csx
fetch HA8tjO5.csx
fetch AXrXKmk.csx
fetch Gnoiwe2.csx
fetch 3LqwWXL.csx
fetch AG2Q9lf.csx
fetch GBJ8gfa.csx
fetch DoXFezE.csx
fetch 064VBmj.csx
fetch Dyhc66b.csx
fetch FlHfO3Z.csx
fetch 3g1udO5.csx
fetch 0RPTioD.csx
fetch B5CTjxw.csx
fetch 95wLmkQ.csx
fetch 2hva9nZ.csx
fetch HiNB8m5.csx
fetch 3CkmYEZ.csx
fetch CQhmgl8.csx
fetch 7yavtog.csx
fetch 0aBeRIq.csx
fetch 0PuPRfa.csx
fetch 8qkoYX9.csx
fetch 3Zb8tqR.csx
fetch G2VN4vN.csx
fetch DMWpdgM.csx
fetch I3Qro05.mp3
fetch 2OJwO4I.mp3
fetch 65RYJ2T.mp3
fetch 5jaStT3.mp3
fetch Hum5Jbp.mp3
fetch 6LcJll9.mp3
fetch AJIsjfj.mp3
fetch 7Dwp5p3.mp3
fetch 3fbOD1r.mp3
fetch IVOTQbW.mp3
fetch 71X8690.mp3
fetch EOa4NM6.mp3
fetch G6S4erO.mp3
fetch 4Ii5Ovz.mp3
fetch 6yCmkRy.mp3
fetch 07AQfuT.csx
fetch 45vhxFn
fetch F14CWAX
fetch 0BDhxZi.csx
fetch EyzVImW
fetch CmfVUsp
fetch 1g7h5Ah.csx
fetch 2WpwGvb
fetch GjHxlWK
fetch 5rdukrb
fetch GcV1mkp
fetch Ch5Dpqg
fetch BPmbItB
fetch 1gRkOdk.csx
fetch 0XkLkUW
fetch DkwWHoY
fetch 0nf8CaW
fetch 1vt1U6s.csx
fetch 7bHHFZb
fetch 0cjz2QM
fetch 2hGgxDb.csx
fetch 1Yv9pbg
fetch Cif1v3S
fetch BX6ku7h
fetch 2oKwTm3.csx
fetch 02rArh8
fetch BxDY0WF
fetch 37VOQXE.csx
fetch Bn3QBOw
fetch C4x40Sh
fetch 38a3gUN.csx
fetch 07f0jYE
fetch 76ilq0Z
fetch 3hLQqBp.csx
fetch DZ4Eopz
fetch 0BdG9Iu
fetch 3kbkMwK.csx
fetch 8eIqT2F
fetch IUFfMXq
fetch 66J7HO6
fetch 3zONozh.csx
fetch CnV7MWP
fetch 8nbodCV
fetch 47T9vw3.csx
fetch 7BA44M8
fetch I8Ke57k
fetch 4jHPnzb.csx
fetch 19gXm4G
fetch 5DQDceT
fetch 6Krqd8K.csx
fetch FPL8v50
fetch 5MEQOTD
fetch CQ5gWBL
fetch 47pGcnn
fetch 6ZpRN0P.csx
fetch Fi8MpFh
fetch F8ljT9P
fetch 79IT59z.csx
fetch AMLY1Qq
fetch DudX5kY
fetch 7Vj3axE.csx
fetch 5b60XMj
fetch IlWrIoI
fetch 7Zlm1CO.csx
fetch EWIAyAW
fetch 7smWsdu
fetch DylgToO
fetch 8dSiIda
fetch 7hozpIN.csx
fetch 9niwiKi
fetch 1AJsQjC
fetch 8PVaYTx.csx
fetch 8Aeh0VG
fetch 04tt92B
fetch 8bILaOQ.csx
fetch 2vTfMQ1
fetch IDdjiXa
fetch 5KOmg1t
fetch 8lTc9sT.csx
fetch BVsK8k2
fetch 5qVfoM3
fetch 91F5LOV.csx
fetch HhKe4e2
fetch Iy8U3ew
fetch 92RPQMe.csx
fetch H4JuB8l
fetch 44PeD5g
fetch AD3Z54M.csx
fetch 1uusV82
fetch 6erC7nC
fetch AHcgK3R.csx
fetch 2InXXrR
fetch 9VT3122
fetch AeQOeJX.csx
fetch 0qY2Dha
fetch EIFaB7W
fetch Al5ESeQ.csx
fetch 7Fx2VmI
fetch 31YVRER
fetch BEKwucl.csx
fetch B0d7GFc
fetch 4m8BrTb
fetch BZ2skgV.csx
fetch 0zcSzLk
fetch 2yp6e1X
fetch BhGRSsg.csx
fetch AYYqIsN
fetch EKo9maH
fetch BjJqafx.csx
fetch 55srWCr
fetch 9MlZ2jC
fetch DC06yJi
fetch 4tOzfgs
fetch I9TBIgg
fetch D1LQN0z
fetch 87esrTW
fetch C88daAH.csx
fetch 9aftpbU
fetch 6wHgGPr
fetch A9xsd67
fetch 9qVG2MV
fetch AexVsyR
fetch 2BlHypU
fetch GFKXkxi
fetch Ct3cOFH.csx
fetch ArOkEiJ
fetch 0dsTfhB
fetch Dhwiz3v.csx
fetch 1mg3FRB
fetch HblbABE
fetch Dk6o49f.csx
fetch FEm8iJg
fetch 8DByX19
fetch Dw8Ga4g.csx
fetch 4ZFEVRm
fetch IMQRPY3
fetch E8Uw6dH.csx
fetch FpzZYpp
fetch 01sZ4jW
fetch EEzOzLH.csx
fetch 11gCM5t
fetch 9fJxkxy
fetch EIi2vll.csx
fetch J7ETn2n
fetch 9Rr17fX
fetch FFrQsD4.csx
fetch BqAdY6A
fetch JLsWKZv
fetch GBODvpT.csx
fetch CMOqDzt
fetch GJjZl5f
fetch GnMract.csx
fetch 48rLuNC
fetch Ijqe8G1
fetch HLePYMn.csx
fetch CQPYb3a
fetch 3uOXIau
fetch HavOhW5.csx
fetch 8GVJPJ5
fetch 22eU9Dg
fetch HyZjxd7.csx
fetch 551UJGa
fetch AQPIpUB
fetch IdqJLAj.csx
fetch 75TCHuF
fetch 6sSUzeP
fetch IjX1ZRA.csx
fetch 2vDDdEf
fetch 4FnI8Dx
fetch 01qq0RT.csx
fetch GgxBrEk
fetch GlbVlYK.mp3
fetch 9OkFkQL.mp3
fetch 0LFvTXp.csx
fetch 8EXL63C
fetch 2SC8ICT.mp3
fetch 0awZ9pN.csx
fetch 2QH5DS9
fetch FKe4Siq.mp3
fetch 0h3h5kt.csx
fetch 3Eqp2en
fetch 0lOMFGI.csx
fetch BFqi94H
fetch 0obiNue.csx
fetch 4iGv4lQ
fetch 13QnG5Y.csx
fetch 78Tv3Xd
fetch 1JD8R0z.csx
fetch DuUwwE6
fetch 1TaWzvW.csx
fetch 2JOCDb2.csx
fetch J3mWr1G
fetch 2ZxnJTy.csx
fetch CG6WckN
fetch 2gpRBK7.csx
fetch B3jFWa7
fetch 2v7C8sr.csx
fetch 6ctCnMS
fetch 3Brxhnq.csx
fetch 3TCpM04
fetch 3GOsqs4.csx
fetch 6ke5RE9
fetch 3L8u1kd.csx
fetch 80kbec7
fetch 3La6y23.csx
fetch AjPjlpC
fetch 3N1Z20t.csx
fetch Bj5o2UH
fetch 3jcev2y.csx
fetch Dq5Twj2
fetch 3rnAoE0.csx
fetch FRnPORj
fetch 3yQsvyB.csx
fetch 1IkeXss
fetch 7ItQKSn.mp3
fetch 4PkSATV.csx
fetch 7XfgCk9
fetch 4nUYSXW.csx
fetch 0yQSXcc
fetch 52gaKav.csx
fetch 9igfxor
fetch 59K4dLh.csx
fetch 1rROcNc
fetch 5D6Zlpq.csx
fetch 8YdyLYT
fetch 5MhCIpe.csx
fetch 4YeMxQJ
fetch 5MjGiWk.csx
fetch ABybWzp
fetch 5UEH7tk.csx
fetch 7UnaU4R
fetch 5ggrte3.csx
fetch 82AZrCU
fetch 5pN8eUl.csx
fetch INApFvi
fetch 62Jk5sm.csx
fetch 6ZPFpph
fetch 65EC00i.csx
fetch EIiz90w
fetch 6T6QyGV.csx
fetch D5xF2JA
fetch 6XuMNxt.csx
fetch FvuTS8R
fetch 6mQoleE.csx
fetch IxemnTG
fetch 6oANOtO.csx
fetch AfdgniI
fetch 8uo4GDc.mp3
fetch 6zRUZyH.csx
fetch HSvVP5u
fetch 770thpB.csx
fetch Gg1YMH0
fetch 7NpJYxI.csx
fetch 2Hm6Pv1
fetch 7VXba0J.csx
fetch 9AZw75Q
fetch 22X43fX.mp3
fetch 7avOO12.csx
fetch 4hjbUZa
fetch 8A05Ec0.csx
fetch 8Cfv9SQ.csx
fetch 2nQ7suh
fetch 8DP12iG.csx
fetch DSbqHUU
fetch 8iujFXV.csx
fetch Aqm5Cbv
fetch 8jkBoMj.csx
fetch HebpJM2
fetch 8lrV8Ji.csx
fetch 1P3ZQRr
fetch 8p4zorE.csx
fetch 3XYPmLM
fetch 8vQWvNp.csx
fetch FFFXl49
fetch 92Bnc4w.csx
fetch BrRIuZ3
fetch 94HoWkl.csx
fetch G63T8NF
fetch 96KnkzZ.csx
fetch 0Q3SP1Q
fetch HGQsNHd.mp3
fetch G0P7Wxx.mp3
fetch 9EBwBrP.csx
fetch 9GPF1Uu.csx
fetch 1eYmsgC
fetch 9KMLdfL.csx
fetch 7d3TWW8
fetch 9TQy7wk.csx
fetch FJwOhov
fetch 5aOJaYt.mp3
fetch A23l19v.csx
fetch 3DFpN9v
fetch A5o4jZd.csx
fetch 37EvbPv
fetch AA2MtqO.csx
fetch 177tql0
fetch AAlfnXS.csx
fetch 41CQvDz
fetch AKtJdfK.csx
fetch 8o6Wpyl
fetch APHVtuy.csx
fetch EF6nJLt
fetch AfMzABi.csx
fetch Ak94TEP.csx
fetch 38KQDdc
fetch ApVtnmy.csx
fetch 53rYRFP
fetch BC1qH4O.csx
fetch 1i9Kppf
fetch BPrZNPj.csx
fetch IkPsjOW
fetch 1HWpMFz.mp3
fetch BQN9IU8.csx
fetch 0vG6TDd
fetch BRureIC.csx
fetch 9BW4fkS
fetch BTt7WvA.csx
fetch 2lKfSEm
fetch BrAKTfn.csx
fetch GJmzWry
fetch Bs8dJHF.csx
fetch CA4LQgM.csx
fetch BWQe21L
fetch CLtcwy9.csx
fetch FSU9mUD
fetch Cyg7SPX.csx
fetch 43MsPnx
fetch Cz6NeM4.csx
fetch FiCW3T9
fetch D8DXcdE.csx
fetch Bsj8CEW
fetch DC01V4B.csx
fetch HnIGWtS
fetch DCTw2qo.csx
fetch AG6lqIl
fetch DEB7hDE.csx
fetch E9JaFa5
fetch DJ7uzzD.csx
fetch 2Caz8fc
fetch DKSalPN.csx
fetch Cr6jLQM
fetch DPGqd5v.csx
fetch 2d9tkoJ
fetch DPuhsSQ.csx
fetch DnAdNuI.csx
fetch AGBkzxF
fetch DrU5f7z.csx
fetch DlgIuxA
fetch DsmZXhb.csx
fetch 5ELC9sz
fetch E7XOHI9.csx
fetch CG23TLm
fetch EEPtBcX.csx
fetch 2E4VWgC
fetch EIqVDxp.csx
fetch 4jfkQEX
fetch EYzHS7P.csx
fetch 78ukV7J
fetch EcXPqtd.csx
fetch AShFQCQ
fetch 8dfOWVk.mp3
fetch EuZUBTO.csx
fetch Dd6yBz2
fetch FSGSejx.csx
fetch HoJU8mc
fetch CjN4owm.mp3
fetch F0L3g6l.mp3
fetch Fb5WBTS.csx
fetch GgpZSor
fetch FFbushT.mp3
fetch FgfqLmk.csx
fetch ER9UpuX
fetch G8wHst6.csx
fetch Covewz0
fetch FVXyOVW.mp3
fetch I87U8Gz.mp3
fetch GRN4G1A.csx
fetch IvLxOOh
fetch GdHCYie.csx
fetch I9UWj6e
fetch Gf2k6zm.csx
fetch G2TxzaY
fetch Got5bOU.csx
fetch 3ZDopNX
fetch H1WKIVJ.csx
fetch 97EckeF
fetch HActZmV.csx
fetch F2SQjVU
fetch HdWQopd.csx
fetch BTf108S
fetch Hyz56Wr.csx
fetch 11FJ3hD
fetch I3z9fc4.csx
fetch EXcBJFo
fetch IDgrR9r.csx
fetch 136t3bS
fetch INtDSsl.csx
fetch 6l8FvEk
fetch IZY7gmz.csx
fetch 4LQaGKG
fetch IgpMTHF.csx
fetch FydqYWe
fetch 0Kx1DCk.csx
fetch 3j56Gqq
fetch 0qrpPuc.csx
fetch 2N7fEKq
fetch GLpQXGR
fetch 10Gy0Lg.csx
fetch DVNBug6
fetch IRIZPhl
fetch 1EOHeqB.csx
fetch DLPfNGk
fetch FdyRmdj
fetch 1Re8NNl.csx
fetch 14JL3Nv
fetch 1f1WRJj.csx
fetch 5hZE57f
fetch 2KaBGrI.csx
fetch BpT8vIo
fetch 2RPnJMH.csx
fetch F1DcTq7
fetch 4uk7eSK
fetch 7YUcCfH
fetch 39tLcHU.csx
fetch A7ZBhKt
fetch 5xkiLa2
fetch 3LB7iph.csx
fetch 2Kb6aZe
fetch 3LewSZ9.csx
fetch 5X5Zr0R
fetch 3PoZJNi.csx
fetch EtKhchn
fetch 1fI77sg
fetch 46JnZae.csx
fetch HgvV4ct
fetch 4pmlS0B.csx
fetch 32YhcG9
fetch 5IbPnUH.csx
fetch 1HNGuLv
fetch BTm81BL
fetch 6p0GBSx.csx
fetch 4dlfRJt
fetch CEW7blt
fetch 7BuGBJG.csx
fetch 0FU7I9i
fetch 7QqIDAN
fetch 8FrAoRl.csx
fetch GBM6TbC
fetch Ef6gMLA
fetch 8Lowbeq.csx
fetch 79BZkMN
fetch 9FqTYfk
fetch 8mk09zO.csx
fetch 02zb57P
fetch 5pX7Jm6
fetch 8onitL7.csx
fetch EegSSlq
fetch 91m2Ldt.csx
fetch 6an0N8v
fetch 954oyQh.csx
fetch 67qZ45N
fetch AcTnenp
fetch 66Nsbms
fetch AYooZsC.csx
fetch 24HMZD1
fetch Ad7Lh6o.csx
fetch 3o8l2SD
fetch AksdbJW.csx
fetch IghLzBJ
fetch Bjtba3p.csx
fetch 1t02jFu
fetch 8oKj1Db
fetch Bth5cLa.csx
fetch FjQjd2R
fetch IcYyaUu
fetch CIYQ2UO.csx
fetch 0Ungvgs
fetch DNxyYp9
fetch CWldzWy.csx
fetch BKThThi
fetch CbDle6m.csx
fetch BYh00DL
fetch Cdxstxg.csx
fetch 8yeqoMT
fetch BjbCcd2
fetch CzuAlHS.csx
fetch GyDTnhM
fetch EuWAjcK.csx
fetch 9VETwoy
fetch 1t2yDg6
fetch Ev0Rg1W.csx
fetch 4JwkvxF
fetch 6qPfE9h
fetch Ex2m5w6.csx
fetch 63SScVm
fetch E4OGcCc
fetch F3DPcG4.csx
fetch 9nEsiDH
fetch FCUgnkJ.csx
fetch FJn12kZ
fetch 171QqBw
fetch FVsETQ8.csx
fetch IIX1G8n
fetch G3whKdI.csx
fetch IbK5bII
fetch H30jgm5.csx
fetch CHKhBDC
fetch 6wnHYpe
fetch H8VXcko.csx
fetch EIXqi7y
fetch 7NSmikm
fetch 2iVvvqI
fetch HGCknYA.csx
fetch CzQagmH
fetch Bvcod86
fetch HvQ83Zf.csx
fetch IST6GnG
fetch 6MPD39A
fetch IhQOucY.csx
fetch 2c5iEij
fetch J3OGSLZ.csx
fetch CV7qN3F
