#!/bin/bash

brew install wget

rm -rf gama
mkdir -p gama
cd gama
rm -rfv *.csx

fetch(){
  if [ -f "$1" ]
  then
    echo "exist: $1"
  else
    URL="http://www.gamagama.cn/fetch/$1"
    echo "fetch: $URL"
    wget $URL
  fi
}


fetch 5IbPnUH.csx


fetch IT6Jdkm.csx
fetch 4X6Mylf
fetch COXOA5U.csx
fetch 0TieIRx
fetch AEutcbZ.csx
fetch AVfgzeV
fetch 3RqXS0i.csx
fetch EH8H2qZ.csx
fetch 7IIKumJ.csx
fetch 2w3zBZ4.csx
fetch Dh7rH2l.csx
fetch 9dzOJ13.csx
fetch 7oDNB5X.csx
fetch GEh2nzA.csx
fetch BAAuo0H.csx
fetch 56PIcLn.csx
fetch ApVuMAi.csx
fetch I2CE4mG.csx
fetch 1SY2u8X.csx
fetch Fzyiy8f.csx
fetch EkiiKz3.csx
fetch 5KwNr5C.csx
fetch EvV4RIb.csx
fetch 5f09w6d.csx
fetch CNtTjVc.csx
fetch G4rwtni.csx
fetch 6GTKomq.csx
fetch GkFQGf1.csx
fetch G6ARs3I.csx
fetch AchL7Zq.csx
fetch BTDIVYx.csx
fetch IZzc8kF.csx
fetch 6ZGELkv.csx
fetch 49vdGXg.csx
fetch 6ni0vrX.csx
fetch HDqNOeo.csx
fetch 2HU14qc.csx
fetch 8nwiDN3.csx
fetch 7Zp2g3h.csx
fetch BiXhgGo.csx
fetch 1cmUyiz.csx
fetch AbHwOXi.csx
fetch FbqpfMG.csx
fetch 013epva.csx
fetch Bi6mXnG.csx
fetch 2EPeBNv.csx
fetch DZioREd.csx
fetch DTwpIZh.csx
fetch Bmx3wik.csx
fetch F3T6xqr.csx
fetch 95lVUvv.csx
fetch HtJP2mi.csx
fetch AynTUsS.csx
fetch EDaOlFJ.csx
fetch 8C2Zv8z.csx
fetch IVCJHsL.csx
fetch 1XOrHmZ.csx
fetch 6CRvoUg.csx
fetch 4X4P6rg.csx
fetch 0MAFaCX.csx
fetch A80R6r8.csx
fetch 5x8Wn7x.csx
fetch GIlmywV.csx
fetch 7ltYRQq.csx
fetch B3hcS7L.csx
fetch EQhYHbN.csx
fetch EG1WHde.csx
fetch 7PRZvGY.csx
fetch 7SPmbv2.csx
fetch 8Qki8Ip.csx
fetch HNtMouH.csx
fetch J78b6ow.csx
fetch 2ktdRkd.csx
fetch Gd48MQM.csx
fetch INhQ6ls.csx
fetch 6qNbRgF.csx
fetch CIw28rT.csx
fetch FexVpcA.csx
fetch 5ocl4VK.csx
fetch FDs45Ya.csx
fetch CqgpXiE.csx
fetch GdT5KT0.csx
fetch 1ENbowR.csx
fetch 7tnk8Fe.csx
fetch 52zQT2h.csx
fetch ArXsZtW.csx
fetch 9qbuEPi.csx
fetch 76nc8I7.csx
fetch J1M2e3F.csx
fetch 0Afxnh5.csx
fetch 3brJb2R.csx
fetch 6EQodrU.csx
fetch 92EYabk.csx
fetch BtSvFhc.csx
fetch 9SeCpF9.csx
fetch ICd7AcC.csx
fetch 9NA86u1.csx
fetch 13NhBdp.csx
fetch Dhry2Os.csx
fetch 0FBnkpS.csx
fetch FmHgrRg.csx
fetch 35yiR3p.csx
fetch 3nMqvrg.csx
fetch 08w3rr9.csx
fetch ICAEEU3.csx
fetch 0Xp1G6R.csx
fetch 804SlNT.csx
fetch 114cKl7.csx
fetch A811lTr.csx
fetch IXImU8a.csx
fetch 7l1Qx8U.csx
fetch 1jZFRMc.csx
fetch Crp2gq2.csx
fetch AVFgmf5.csx
fetch 9bfjfqr.csx
fetch 0mcIs3l.csx
fetch 8tr82jW.csx
fetch 8HSO2b4.csx
fetch FeteblS.csx
fetch DY8qg1E.csx
fetch 9ghAog8.csx
fetch DLqJnkc.csx
fetch HkYuF0P.csx
fetch FaQsyAD.csx
fetch 0UcsUWc.csx
fetch IyLR0h6.csx
fetch GJJOmaJ.csx
fetch 9LUEqzO.csx
fetch 1GoPJgX.csx
fetch 47nbzva.csx
fetch GskP3WX.csx
fetch 95Aks4d.csx
fetch CwST5os.csx
fetch 7ezYOtf.csx
fetch 6YZR7pb.csx
fetch 28zF6iI.csx
fetch 6l5LZKb.csx
fetch GyDCnt8.csx
fetch HA8tjO5.csx
fetch AXrXKmk.csx
fetch Gnoiwe2.csx
fetch 3LqwWXL.csx
fetch AG2Q9lf.csx
fetch GBJ8gfa.csx
fetch DoXFezE.csx
fetch 064VBmj.csx
fetch Dyhc66b.csx
fetch FlHfO3Z.csx
fetch 3g1udO5.csx
fetch 0RPTioD.csx
fetch B5CTjxw.csx
fetch 95wLmkQ.csx
fetch 2hva9nZ.csx
fetch HiNB8m5.csx
fetch 3CkmYEZ.csx
fetch CQhmgl8.csx
fetch 7yavtog.csx
fetch 0aBeRIq.csx
fetch 0PuPRfa.csx
fetch 8qkoYX9.csx
fetch 3Zb8tqR.csx
fetch G2VN4vN.csx
fetch DMWpdgM.csx
fetch I3Qro05.mp3
fetch 2OJwO4I.mp3
fetch 65RYJ2T.mp3
fetch 5jaStT3.mp3
fetch Hum5Jbp.mp3
fetch 6LcJll9.mp3
fetch AJIsjfj.mp3
fetch 7Dwp5p3.mp3
fetch 3fbOD1r.mp3
fetch IVOTQbW.mp3
fetch 71X8690.mp3
fetch EOa4NM6.mp3
fetch G6S4erO.mp3
fetch 4Ii5Ovz.mp3
fetch 6yCmkRy.mp3
fetch 07AQfuT.csx
fetch 1FOLQqP
fetch 9PNkDxS
fetch 0BDhxZi.csx
fetch FYmAmjM
fetch 9nAFzFF
fetch 1g7h5Ah.csx
fetch 5A4rpDr
fetch 9h06pHQ
fetch 4vQVpxw
fetch 2tHl3Mf
fetch 2g1IRXt
fetch G9iZncp
fetch 1gRkOdk.csx
fetch 1EEd93w
fetch I2G9oqx
fetch 9EGNhcL
fetch 1vt1U6s.csx
fetch BMvWAXB
fetch EOE9dDc
fetch 2hGgxDb.csx
fetch 1B4nXT0
fetch J85YGHG
fetch 4ripdU5
fetch 2oKwTm3.csx
fetch EgvtZJJ
fetch 7VCg30N
fetch 37VOQXE.csx
fetch Bc6rWRq
fetch IOoIhKH
fetch 38a3gUN.csx
fetch 7rNBhOJ
fetch DdusOgx
fetch 3hLQqBp.csx
fetch 0UsszBT
fetch 06cPU5G
fetch 3kbkMwK.csx
fetch CsmhNpF
fetch 1WuZuD1
fetch Gey2RoD
fetch 3zONozh.csx
fetch APijgUX
fetch 5yamjpA
fetch 47T9vw3.csx
fetch 8E71Qej
fetch 7HexFdW
fetch 4jHPnzb.csx
fetch 6mDuUr8
fetch J4s08Lr
fetch 6Krqd8K.csx
fetch FSxghJj
fetch AdUOgUo
fetch 6RsV51k
fetch DJn4P6x
fetch 6ZpRN0P.csx
fetch G8fSZZ3
fetch 2jlsJs3
fetch 79IT59z.csx
fetch 6pMw6eE
fetch 2ef3vBB
fetch 7Vj3axE.csx
fetch BwGGtCq
fetch 7NgNODo
fetch 7Zlm1CO.csx
fetch AOXq4xn
fetch 0CukyPi
fetch 2evzCUt
fetch DJapPrl
fetch 7hozpIN.csx
fetch EGspnKH
fetch 7zTun1a
fetch 8PVaYTx.csx
fetch IIByJ0s
fetch EMW97Nz
fetch 8bILaOQ.csx
fetch BnOcCM3
fetch 4eZ4Coq
fetch AKR7Q4y
fetch 8lTc9sT.csx
fetch 6Xvc3cz
fetch 83lXufE
fetch 91F5LOV.csx
fetch 8meMIgT
fetch 2QCeyBU
fetch 92RPQMe.csx
fetch 4z4WGrw
fetch 1fsdu1Q
fetch AD3Z54M.csx
fetch 6pxIORz
fetch 95SMjtJ
fetch AHcgK3R.csx
fetch AiSpInt
fetch Dx2xZpt
fetch AeQOeJX.csx
fetch 6wAw2Lh
fetch HIzevKK
fetch Al5ESeQ.csx
fetch 1L1HwDS
fetch Bueq2vX
fetch BEKwucl.csx
fetch 2Nqd32g
fetch 0gYqIgd
fetch BZ2skgV.csx
fetch 8DPY7LV
fetch DGxLSuq
fetch BhGRSsg.csx
fetch 6Yr82QN
fetch ANHbY0d
fetch BjJqafx.csx
fetch Fg1L0GF
fetch 5pDIImS
fetch FqZxjmz
fetch 9hga9lb
fetch 0mXBO7T
fetch FEDWoBM
fetch 0HiCFMu
fetch C88daAH.csx
fetch 6x8PyJX
fetch D9jLMqy
fetch BGSRtoR
fetch 1HA6bAR
fetch 05bPusQ
fetch F2nSYdN
fetch 5icm6H1
fetch Ct3cOFH.csx
fetch 5NfOynv
fetch 88lZyk6
fetch Dhwiz3v.csx
fetch IegTV78
fetch 5ZjVzMH
fetch Dk6o49f.csx
fetch 2vFnCrx
fetch GpvY6E6
fetch Dw8Ga4g.csx
fetch 5xnGKHx
fetch 2XFzGwe
fetch E8Uw6dH.csx
fetch DbRPbVq
fetch 1voWEeO
fetch EEzOzLH.csx
fetch 9KYL7oS
fetch 6JBWMiN
fetch EIi2vll.csx
fetch 9x8BbW3
fetch IGgWmII
fetch FFrQsD4.csx
fetch A7zO9wB
fetch 1LiCyEK
fetch GBODvpT.csx
fetch EyIeESb
fetch FG6sZaF
fetch GnMract.csx
fetch 3xLfFvb
fetch EVTnRSI
fetch HLePYMn.csx
fetch F52FBsE
fetch BsCasy4
fetch HavOhW5.csx
fetch ELDmxv2
fetch 271y5qo
fetch HyZjxd7.csx
fetch CUsqFHf
fetch 0v7W63K
fetch IdqJLAj.csx
fetch 0X3xjIl
fetch 0xDzAp2
fetch IjX1ZRA.csx
fetch 9sM6dXD
fetch 5bHGJ6E
fetch 01qq0RT.csx
fetch 3W5Y7G6
fetch GlbVlYK.mp3
fetch 9OkFkQL.mp3
fetch 0LFvTXp.csx
fetch 0CcVqCO
fetch 2SC8ICT.mp3
fetch 0awZ9pN.csx
fetch FtlYvcZ
fetch FKe4Siq.mp3
fetch 0h3h5kt.csx
fetch 2kci5Un
fetch 0lOMFGI.csx
fetch 5KEuLs1
fetch 0obiNue.csx
fetch FV9DHmb
fetch 13QnG5Y.csx
fetch 8432drX
fetch 1JD8R0z.csx
fetch 6QMvBIs
fetch 1TaWzvW.csx
fetch 2JOCDb2.csx
fetch 4RWMK2Q
fetch 2ZxnJTy.csx
fetch CjGHMpw
fetch 2gpRBK7.csx
fetch 2p2QWWE
fetch 2v7C8sr.csx
fetch 1OEPOyM
fetch 3Brxhnq.csx
fetch 6hSql5K
fetch 3GOsqs4.csx
fetch C80mNlt
fetch 3L8u1kd.csx
fetch 9LIpBd7
fetch 3La6y23.csx
fetch IZsrLcg
fetch 3N1Z20t.csx
fetch FDeFEnA
fetch 3jcev2y.csx
fetch E9w33jv
fetch 3rnAoE0.csx
fetch 2ueVVsd
fetch 3yQsvyB.csx
fetch 4hjK93e
fetch 7ItQKSn.mp3
fetch 4PkSATV.csx
fetch 0oqnzC1
fetch 4nUYSXW.csx
fetch 75tVNLZ
fetch 52gaKav.csx
fetch 4hPqAcE
fetch 59K4dLh.csx
fetch 6aF6v5V
fetch 5D6Zlpq.csx
fetch 1tf111E
fetch 5MhCIpe.csx
fetch HKdpeF3
fetch 5MjGiWk.csx
fetch CshoiMT
fetch 5UEH7tk.csx
fetch 0tcwdml
fetch 5ggrte3.csx
fetch ARLiOM3
fetch 5pN8eUl.csx
fetch D7N0nXH
fetch 62Jk5sm.csx
fetch Dzw8isw
fetch 65EC00i.csx
fetch 9QTfWjS
fetch 6T6QyGV.csx
fetch HTL6F8C
fetch 6XuMNxt.csx
fetch DvRZNxK
fetch 6mQoleE.csx
fetch BMT5Ozm
fetch 6oANOtO.csx
fetch 6wbORcH
fetch 8uo4GDc.mp3
fetch 6zRUZyH.csx
fetch DfBeeqt
fetch 770thpB.csx
fetch AyPaeBT
fetch 7NpJYxI.csx
fetch Htf9McB
fetch 7VXba0J.csx
fetch 42xkivs
fetch 22X43fX.mp3
fetch 7avOO12.csx
fetch 0kH8JtB
fetch 8A05Ec0.csx
fetch 8Cfv9SQ.csx
fetch 7yZ1FHh
fetch 8DP12iG.csx
fetch GDCW0Nx
fetch 8iujFXV.csx
fetch 16YsFow
fetch 8jkBoMj.csx
fetch BDk2rSP
fetch 8lrV8Ji.csx
fetch 5mtrfsM
fetch 8p4zorE.csx
fetch FH25gy8
fetch 8vQWvNp.csx
fetch 7qnSFpx
fetch 92Bnc4w.csx
fetch 6ay3nHe
fetch 94HoWkl.csx
fetch JHJaTB3
fetch 96KnkzZ.csx
fetch 6okexrW
fetch HGQsNHd.mp3
fetch G0P7Wxx.mp3
fetch 9EBwBrP.csx
fetch 9GPF1Uu.csx
fetch 4AwYGit
fetch 9KMLdfL.csx
fetch IGTgAJ2
fetch 9TQy7wk.csx
fetch 4433yIZ
fetch 5aOJaYt.mp3
fetch A23l19v.csx
fetch EQBzUDv
fetch A5o4jZd.csx
fetch 2OyPmfG
fetch AA2MtqO.csx
fetch 4BwXW8Y
fetch AAlfnXS.csx
fetch E0GLE2r
fetch AKtJdfK.csx
fetch 2ZISR4L
fetch APHVtuy.csx
fetch GB3xGZQ
fetch AfMzABi.csx
fetch Ak94TEP.csx
fetch 090Dudy
fetch ApVtnmy.csx
fetch 0fCB1gq
fetch BC1qH4O.csx
fetch 9mkj6wj
fetch BPrZNPj.csx
fetch 1Am7Y5E
fetch 1HWpMFz.mp3
fetch BQN9IU8.csx
fetch 6uUpvbU
fetch BRureIC.csx
fetch CgwHNb6
fetch BTt7WvA.csx
fetch 32GqWNU
fetch BrAKTfn.csx
fetch 608UzCR
fetch Bs8dJHF.csx
fetch CA4LQgM.csx
fetch IJD7sTK
fetch CLtcwy9.csx
fetch EsstGgu
fetch Cyg7SPX.csx
fetch 5GOXd8y
fetch Cz6NeM4.csx
fetch DPsY1Uf
fetch D8DXcdE.csx
fetch 3eFHIbP
fetch DC01V4B.csx
fetch 6q0kjpK
fetch DCTw2qo.csx
fetch CsgkpsF
fetch DEB7hDE.csx
fetch FxFN7Dn
fetch DJ7uzzD.csx
fetch 7E3ezYc
fetch DKSalPN.csx
fetch 8mbuTV4
fetch DPGqd5v.csx
fetch 2UArXx3
fetch DPuhsSQ.csx
fetch DnAdNuI.csx
fetch E2MLzDg
fetch DrU5f7z.csx
fetch GIKGgb5
fetch DsmZXhb.csx
fetch FKheTnm
fetch E7XOHI9.csx
fetch 8kKG4EU
fetch EEPtBcX.csx
fetch 9OYBWOa
fetch EIqVDxp.csx
fetch BzJfLFe
fetch EYzHS7P.csx
fetch 2XdEIQ6
fetch EcXPqtd.csx
fetch IJW49iP
fetch 8dfOWVk.mp3
fetch EuZUBTO.csx
fetch Aq95gu4
fetch FSGSejx.csx
fetch DlHMy7C
fetch CjN4owm.mp3
fetch F0L3g6l.mp3
fetch Fb5WBTS.csx
fetch CTJ3k2u
fetch FFbushT.mp3
fetch FgfqLmk.csx
fetch AkV76e7
fetch G8wHst6.csx
fetch BaI7CsJ
fetch FVXyOVW.mp3
fetch I87U8Gz.mp3
fetch GRN4G1A.csx
fetch 0TbCLWu
fetch GdHCYie.csx
fetch 4LnxVr3
fetch Gf2k6zm.csx
fetch HPoybK6
fetch Got5bOU.csx
fetch DRlYRGO
fetch H1WKIVJ.csx
fetch 4fb3Gov
fetch HActZmV.csx
fetch DeDMSkJ
fetch HdWQopd.csx
fetch Dc3Hb1s
fetch Hyz56Wr.csx
fetch Hz1ieAU
fetch I3z9fc4.csx
fetch 3zUnGJ8
fetch IDgrR9r.csx
fetch Cgd6lvQ
fetch INtDSsl.csx
fetch ByQSSaG
fetch IZY7gmz.csx
fetch B5Yd7q5
fetch IgpMTHF.csx
fetch H0rFddF
fetch 0Kx1DCk.csx
fetch 2WzOPTF
fetch 0qrpPuc.csx
fetch ITSea9z
fetch 3bVtqJ0
fetch 10Gy0Lg.csx
fetch 1Z3hPGC
fetch B2mLMBN
fetch 1EOHeqB.csx
fetch BXPnVCr
fetch FbfMnDC
fetch 1Re8NNl.csx
fetch 7bYztUv
fetch 1f1WRJj.csx
fetch HDvORoB
fetch 2KaBGrI.csx
fetch 2WJSb8n
fetch 2RPnJMH.csx
fetch 4a6SCR8
fetch 38V4Yuu
fetch DUMZXNY
fetch 39tLcHU.csx
fetch 9xgHAPs
fetch 3o8j1VI
fetch 3LB7iph.csx
fetch ApM9JXi
fetch 3LewSZ9.csx
fetch 9WkJ8Y3
fetch 3PoZJNi.csx
fetch 9nZNRnt
fetch DoD35GW
fetch 46JnZae.csx
fetch 0BSE3rI
fetch 4pmlS0B.csx
fetch 1awykYV
fetch 5IbPnUH.csx
fetch 47XvBiI
fetch AN2T672
fetch 6p0GBSx.csx
fetch EpZIvdw
fetch 5NiW93n
fetch 7BuGBJG.csx
fetch CdTDzHq
fetch 87cpp2d
fetch 8FrAoRl.csx
fetch 4A0S9uQ
fetch 75nEPrm
fetch 8Lowbeq.csx
fetch 2mKI1Sx
fetch 0Bhpj7w
fetch 8mk09zO.csx
fetch HYDQ06z
fetch 76C4cEH
fetch 8onitL7.csx
fetch 9JaOp5h
fetch 91m2Ldt.csx
fetch IWS8Dcu
fetch 954oyQh.csx
fetch CGkIr6C
fetch 6I7IvJP
fetch GSElEtO
fetch AYooZsC.csx
fetch B7ro0K5
fetch Ad7Lh6o.csx
fetch HQXOhTU
fetch AksdbJW.csx
fetch 0N7VlCX
fetch Bjtba3p.csx
fetch FiFpKDi
fetch AJZZmsd
fetch Bth5cLa.csx
fetch 147euXd
fetch 6uLGfU0
fetch CIYQ2UO.csx
fetch CDLCdwt
fetch CMqamdx
fetch CWldzWy.csx
fetch 4TvzKLw
fetch CbDle6m.csx
fetch 84OpWbf
fetch Cdxstxg.csx
fetch 6S8EWuy
fetch IeAk8l4
fetch CzuAlHS.csx
fetch HfiXt5F
fetch EuWAjcK.csx
fetch FXGqG61
fetch 8RQm3YY
fetch Ev0Rg1W.csx
fetch BlzPrPl
fetch 9XWKCph
fetch Ex2m5w6.csx
fetch CL1OoyZ
fetch 7HypbRI
fetch F3DPcG4.csx
fetch 6KyIe8h
fetch FCUgnkJ.csx
fetch DAwPzUt
fetch DtcaawC
fetch FVsETQ8.csx
fetch 6qv3tqP
fetch G3whKdI.csx
fetch Fjm6Crd
fetch H30jgm5.csx
fetch G2dScUI
fetch Dl9NSnf
fetch H8VXcko.csx
fetch HWct8oA
fetch 8okBMu5
fetch 3n6rlCc
fetch HGCknYA.csx
fetch FwwygEd
fetch FTHWxPo
fetch HvQ83Zf.csx
fetch E2Ot9Rh
fetch 5LmL4kz
fetch IhQOucY.csx
fetch 7A5jVZI
fetch J3OGSLZ.csx
fetch 3KHH4Cj
