#!/bin/bash

brew install wget

#rm -rf gama
mkdir -p gama
cd gama
rm -rfv *.csx

fetch(){
  if [ -f "$1" ]
  then
    echo "exist: $1"
  else
    URL="http://www.gamagama.cn/fetch/$1"
    echo "fetch: $URL"
    wget $URL
  fi
}


fetch 8DP12iG.csx
fetch DSbqHUU

fetch 5IbPnUH.csx
fetch 6IwNfWP
fetch DpbOuXt
fetch 954oyQh.csx
fetch 67qZ45N
fetch AcTnenp
fetch 66Nsbms


fetch 3RqXS0i.csx
fetch EH8H2qZ.csx
fetch 7IIKumJ.csx
fetch EDaOlFJ.csx
fetch 2w3zBZ4.csx
fetch HDqNOeo.csx
fetch 6ni0vrX.csx
fetch Dh7rH2l.csx
fetch 9dzOJ13.csx
fetch 7oDNB5X.csx
fetch GEh2nzA.csx
fetch BAAuo0H.csx
fetch 49vdGXg.csx
fetch AchL7Zq.csx
fetch DTwpIZh.csx
fetch BTDIVYx.csx
fetch GkFQGf1.csx
fetch G6ARs3I.csx
fetch 8C2Zv8z.csx
fetch HtJP2mi.csx
fetch 6GTKomq.csx
fetch DZioREd.csx
fetch AynTUsS.csx
fetch 6ZGELkv.csx
fetch IZzc8kF.csx
fetch F3T6xqr.csx
fetch Bmx3wik.csx
fetch 95lVUvv.csx
fetch 56PIcLn.csx
fetch ApVuMAi.csx
fetch I2CE4mG.csx
fetch 1SY2u8X.csx
fetch Fzyiy8f.csx
fetch G4rwtni.csx
fetch EkiiKz3.csx
fetch 5KwNr5C.csx
fetch EvV4RIb.csx
fetch 5f09w6d.csx
fetch CNtTjVc.csx
fetch 2EPeBNv.csx
fetch 2HU14qc.csx
fetch 8nwiDN3.csx
fetch 7Zp2g3h.csx
fetch BiXhgGo.csx
fetch 1cmUyiz.csx
fetch AbHwOXi.csx
fetch FbqpfMG.csx
fetch 013epva.csx
fetch Bi6mXnG.csx
fetch F8ufYMk.csx
fetch 699D4rc.csx
fetch 5sGjndp.csx
fetch DjVzhcz.csx
fetch GIlmywV.csx
fetch 6CRvoUg.csx
fetch 4X4P6rg.csx
fetch 0MAFaCX.csx
fetch A80R6r8.csx
fetch 5x8Wn7x.csx
fetch 9tmT8cE.csx
fetch HWzH2h2.csx
fetch 5VgsADk.csx
fetch BQekwG8.csx
fetch 3LFaCQ5.csx
fetch 1RQReU7.csx
fetch 4fIlSQX.csx
fetch FsW0jj7.csx
fetch D6IjNIk.csx
fetch 1ClOIiM.csx
fetch HLArlO7.csx
fetch A6w5DDa.csx
fetch A6AQpdn.csx
fetch FQKzcNz.csx
fetch GfAs26k.csx
fetch 4XFjK6A.csx
fetch FdDFzff.csx
fetch F1tkHdu.csx
fetch 3wmqdIT.csx
fetch ANZEl7e.csx
fetch FF1iYdp.csx
fetch 5NVLLZl.csx
fetch 05dK9Ep.csx
fetch AWFloCT.csx
fetch 6YZR7pb.csx
fetch 28zF6iI.csx
fetch 47nbzva.csx
fetch Crp2gq2.csx
fetch AVFgmf5.csx
fetch 9bfjfqr.csx
fetch 0mcIs3l.csx
fetch 11rX8L1.csx
fetch C4phQXp.csx
fetch IYauvHO.csx
fetch GHYQbNn.csx
fetch 80sik2W.csx
fetch 5dQ54Li.csx
fetch IIZi9EO.csx
fetch J81KHYu.csx
fetch 2xyWSvC.csx
fetch 796stob.csx
fetch COHxJsX.csx
fetch ELFE1mq.csx
fetch 7YvQKK5.csx
fetch 7ezYOtf.csx
fetch GskP3WX.csx
fetch 95Aks4d.csx
fetch CwST5os.csx
fetch 07AQfuT.csx
fetch 45vhxFn
fetch F14CWAX
fetch 0BDhxZi.csx
fetch EyzVImW
fetch CmfVUsp
fetch 1g7h5Ah.csx
fetch 2WpwGvb
fetch GjHxlWK
fetch 5rdukrb
fetch GcV1mkp
fetch Ch5Dpqg
fetch BPmbItB
fetch 1gRkOdk.csx
fetch 0XkLkUW
fetch DkwWHoY
fetch 0nf8CaW
fetch 1vt1U6s.csx
fetch 7bHHFZb
fetch 0cjz2QM
fetch 2hGgxDb.csx
fetch 1Yv9pbg
fetch Cif1v3S
fetch BX6ku7h
fetch 2oKwTm3.csx
fetch 02rArh8
fetch BxDY0WF
fetch 37VOQXE.csx
fetch Bn3QBOw
fetch C4x40Sh
fetch 38a3gUN.csx
fetch 07f0jYE
fetch 76ilq0Z
fetch 3hLQqBp.csx
fetch DZ4Eopz
fetch 0BdG9Iu
fetch 3kbkMwK.csx
fetch 8eIqT2F
fetch IUFfMXq
fetch 66J7HO6
fetch 3zONozh.csx
fetch CnV7MWP
fetch 8nbodCV
fetch 47T9vw3.csx
fetch 7BA44M8
fetch I8Ke57k
fetch 4jHPnzb.csx
fetch 19gXm4G
fetch 5DQDceT
fetch 6Krqd8K.csx
fetch FPL8v50
fetch 5MEQOTD
fetch CQ5gWBL
fetch 47pGcnn
fetch 6ZpRN0P.csx
fetch Fi8MpFh
fetch F8ljT9P
fetch 79IT59z.csx
fetch AMLY1Qq
fetch DudX5kY
fetch 7Vj3axE.csx
fetch 5b60XMj
fetch IlWrIoI
fetch 7Zlm1CO.csx
fetch EWIAyAW
fetch 7smWsdu
fetch DylgToO
fetch 8dSiIda
fetch 7hozpIN.csx
fetch 9niwiKi
fetch 1AJsQjC
fetch 8PVaYTx.csx
fetch 8Aeh0VG
fetch 04tt92B
fetch 8bILaOQ.csx
fetch 2vTfMQ1
fetch IDdjiXa
fetch 5KOmg1t
fetch 8lTc9sT.csx
fetch BVsK8k2
fetch 5qVfoM3
fetch 91F5LOV.csx
fetch HhKe4e2
fetch Iy8U3ew
fetch 92RPQMe.csx
fetch H4JuB8l
fetch 44PeD5g
fetch AD3Z54M.csx
fetch 1uusV82
fetch 6erC7nC
fetch AHcgK3R.csx
fetch 2InXXrR
fetch 9VT3122
fetch AeQOeJX.csx
fetch 0qY2Dha
fetch EIFaB7W
fetch Al5ESeQ.csx
fetch 7Fx2VmI
fetch 31YVRER
fetch BEKwucl.csx
fetch B0d7GFc
fetch 4m8BrTb
fetch BZ2skgV.csx
fetch 0zcSzLk
fetch 2yp6e1X
fetch BhGRSsg.csx
fetch AYYqIsN
fetch EKo9maH
fetch BjJqafx.csx
fetch 55srWCr
fetch 9MlZ2jC
fetch DC06yJi
fetch 4tOzfgs
fetch I9TBIgg
fetch D1LQN0z
fetch 87esrTW
fetch C88daAH.csx
fetch 9aftpbU
fetch 6wHgGPr
fetch A9xsd67
fetch 9qVG2MV
fetch AexVsyR
fetch 2BlHypU
fetch GFKXkxi
fetch Ct3cOFH.csx
fetch ArOkEiJ
fetch 0dsTfhB
fetch Dhwiz3v.csx
fetch 1mg3FRB
fetch HblbABE
fetch Dk6o49f.csx
fetch FEm8iJg
fetch 8DByX19
fetch Dw8Ga4g.csx
fetch 4ZFEVRm
fetch IMQRPY3
fetch E8Uw6dH.csx
fetch FpzZYpp
fetch 01sZ4jW
fetch EEzOzLH.csx
fetch 11gCM5t
fetch 9fJxkxy
fetch EIi2vll.csx
fetch J7ETn2n
fetch 9Rr17fX
fetch FFrQsD4.csx
fetch BqAdY6A
fetch JLsWKZv
fetch GBODvpT.csx
fetch CMOqDzt
fetch GJjZl5f
fetch GnMract.csx
fetch 48rLuNC
fetch Ijqe8G1
fetch HLePYMn.csx
fetch CQPYb3a
fetch 3uOXIau
fetch HavOhW5.csx
fetch 8GVJPJ5
fetch 22eU9Dg
fetch HyZjxd7.csx
fetch 551UJGa
fetch AQPIpUB
fetch IdqJLAj.csx
fetch 75TCHuF
fetch 6sSUzeP
fetch IjX1ZRA.csx
fetch 2vDDdEf
fetch 4FnI8Dx
fetch 0h3h5kt.csx
fetch 0obiNue.csx
fetch 13QnG5Y.csx
fetch 78Tv3Xd
fetch 1TaWzvW.csx
fetch 2W9t3OC.csx
fetch 2ZxnJTy.csx
fetch CG6WckN
fetch 2gpRBK7.csx
fetch 2v7C8sr.csx
fetch 3GOsqs4.csx
fetch 6ke5RE9
fetch 3N1Z20t.csx
fetch Bj5o2UH
fetch 3rnAoE0.csx
fetch FRnPORj
fetch 4PkSATV.csx
fetch 7XfgCk9
fetch 52gaKav.csx
fetch 59K4dLh.csx
fetch 5D6Zlpq.csx
fetch 8YdyLYT
fetch 5MjGiWk.csx
fetch 5ggrte3.csx
fetch 82AZrCU
fetch 62Jk5sm.csx
fetch 6ZPFpph
fetch 65EC00i.csx
fetch 6T6QyGV.csx
fetch D5xF2JA
fetch 6mQoleE.csx
fetch IxemnTG
fetch 770thpB.csx
fetch 7NpJYxI.csx
fetch 2Hm6Pv1
fetch 7avOO12.csx
fetch 8A05Ec0.csx
fetch 8Cfv9SQ.csx
fetch 2nQ7suh
fetch 8iujFXV.csx
fetch 8jkBoMj.csx
fetch 8lrV8Ji.csx
fetch 1P3ZQRr
fetch 8p4zorE.csx
fetch 8vQWvNp.csx
fetch FFFXl49
fetch 9EBwBrP.csx
fetch 9GPF1Uu.csx
fetch 1eYmsgC
fetch A5o4jZd.csx
fetch 37EvbPv
fetch AKtJdfK.csx
fetch 8o6Wpyl
fetch AfMzABi.csx
fetch ApVtnmy.csx
fetch BC1qH4O.csx
fetch BRureIC.csx
fetch 9BW4fkS
fetch BTt7WvA.csx
fetch 2lKfSEm
fetch BrAKTfn.csx
fetch Bs8dJHF.csx
fetch CA4LQgM.csx
fetch CLtcwy9.csx
fetch Cyg7SPX.csx
fetch DC01V4B.csx
fetch DCTw2qo.csx
fetch DEB7hDE.csx
fetch DP3ddpe
fetch DJ7uzzD.csx
fetch DKSalPN.csx
fetch DPGqd5v.csx
fetch DPuhsSQ.csx
fetch DnAdNuI.csx
fetch AGBkzxF
fetch DrU5f7z.csx
fetch DlgIuxA
fetch E7XOHI9.csx
fetch CG23TLm
fetch EEPtBcX.csx
fetch EIqVDxp.csx
fetch 4jfkQEX
fetch EYzHS7P.csx
fetch EuZUBTO.csx
fetch FNPqAeu.csx
fetch FgfqLmk.csx
fetch ER9UpuX
fetch GRN4G1A.csx
fetch GdHCYie.csx
fetch Gf2k6zm.csx
fetch H1WKIVJ.csx
fetch HdWQopd.csx
fetch Hyz56Wr.csx
fetch I3z9fc4.csx
fetch EXcBJFo
fetch IZY7gmz.csx
fetch 4LQaGKG
fetch IgpMTHF.csx
fetch 10Gy0Lg.csx
fetch DVNBug6
fetch IRIZPhl
fetch 1f1WRJj.csx
fetch 7NAIF5x
fetch 2RPnJMH.csx
fetch 2hUWDqe.csx
fetch 6GRTvK3
fetch 7f4uVkm
fetch 39tLcHU.csx
fetch A7ZBhKt
fetch 5xkiLa2
fetch 3LB7iph.csx
fetch CqUvOwj
fetch 3PoZJNi.csx
fetch 4jAud82
fetch 0XJOVRS
fetch 5IbPnUH.csx
fetch 6IwNfWP
fetch DpbOuXt
fetch 6p0GBSx.csx
fetch 4dlfRJt
fetch CEW7blt
fetch 8Lowbeq.csx
fetch 79BZkMN
fetch 9FqTYfk
fetch 8mk09zO.csx
fetch 02zb57P
fetch 5pX7Jm6
fetch 8xQsTDE.csx
fetch 6NxVFrR
fetch 91m2Ldt.csx
fetch 6an0N8v
fetch AcPIXKX.csx
fetch Bjtba3p.csx
fetch 1t02jFu
fetch 8oKj1Db
fetch CIYQ2UO.csx
fetch 0Ungvgs
fetch DNxyYp9
fetch Cdxstxg.csx
fetch 8yeqoMT
fetch BjbCcd2
fetch EuWAjcK.csx
fetch Bkmu8SO
fetch 2FL5z10
fetch Ex2m5w6.csx
fetch 63SScVm
fetch E4OGcCc
fetch F3DPcG4.csx
fetch I1gnOOM
fetch FCUgnkJ.csx
fetch FJn12kZ
fetch 171QqBw
fetch G3whKdI.csx
fetch Gj5xtVa
fetch H30jgm5.csx
fetch CHKhBDC
fetch 6wnHYpe
fetch H8VXcko.csx
fetch EIXqi7y
fetch 7NSmikm
fetch 2iVvvqI
fetch IhQOucY.csx
fetch 57U6wTn
